name: CI

on:
  # Never add pull_request or pull_request_target triggers for security reasons
  push:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'

      - run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_CI_AUTH_TOKEN }}

      - run: npm run typecheck

      - run: npm run test
